### ISSUE TITLE
Multiple operator+ cannot be compile

### ISSUE THREAD

**Issue by Vizepi** [RobloxResearch/SIMDString#10]
There are 4 variant of operator+ that cannot compile:
```c++
SIMDString operator+(const SIMDString&& s1, SIMDString&& s2);
SIMDString operator+(const SIMDString&& s1, const SIMDString& s2);
SIMDString operator+(const SIMDString&& s1, const typename SIMDString::value_type* rhs);
SIMDString operator+(const SIMDString&& s1, const typename SIMDString::value_type rhs);
```

All this variations call `s1.append(...)`, but s1 is const while append cannot be const due to its mutator nature.

Removing the const before s1 solves the issue.

**Comment by linwansong** [comment]
This should be fixed as of https://github.com/RobloxResearch/SIMDString/commit/849525764519d973e2976e947dc30868f3a9c5c0
