### ISSUE TITLE
G3D dependency.

### ISSUE THREAD

**Issue by kingc8** [RobloxResearch/SIMDString#2]
Hello,

Thanks very much for this great work.

Just a quick question, it seems as though G3D headers are required behind it. Going to the G3D website, the main way of downloading the project seems to be a cmd file that pulls down all sorts of setup and attempts to configure my Visual Studio.

Is there another option to less violently satisfy the G3D headers for this implementation?

Thanks again,
Cameron

**Comment by Vizepi** [comment]
You don't need it if you
#define NO_G3D_ALLOCATOR 1
before including SIMDString.h

**Comment by kingc8** [comment]
That's perfect, thank you.

Please close.
