### ISSUE TITLE
std::swap being used with ptrs

### ISSUE THREAD

**Issue by vxw77** [RobloxResearch/SIMDString#3]
https://github.com/RobloxResearch/SIMDString/blob/cc6198791337db6dccd598090fc7b68c51bb5729/SIMDString.h#L147

When SSE is used, the contents of the memory are swapped whereas in the non SSE implementation just the pointers are swapped, is that expected ?

**Comment by Vizepi** [comment]
This is a nasty bug, as the swap here does absolutely nothing.
It would've work if buf1 and buf2 were references/pointers to pointers.

**Comment by linwansong** [comment]
This has been fixed in https://github.com/RobloxResearch/SIMDString/commit/80d371c28a504d9283e68e45902a04af77d5783a
