### ISSUE TITLE
Move constructor swaps uninitialized data which causes crash in destructor

### ISSUE THREAD

**Issue by Vizepi** [RobloxResearch/SIMDString#7]
The move constructor is defined as:
```c++
constexpr SIMDString(SIMDString&& str) {
    swap(str);
}
```
The problem is that `m_data` and `m_allocated` are uninitialized at this point. When the swapped SIMDString is destructed, it executes this code:
```c++
if (m_data && m_allocated) {
    // Note that this calls the method, not ::free 
    free(m_data, m_allocated);
}
```
and because m_data and m_allocated were swapped with uninitialized garbage, the free function is randomly called, freeing random pointer.
Initializing `m_data` to `nullptr` before swap in move constructor fixes the issue.

**Comment by linwansong** [comment]
This has been fixed as of https://github.com/RobloxResearch/SIMDString/commit/849525764519d973e2976e947dc30868f3a9c5c0 . In this version, free is only called when `inHeap` returns true. For an uninitialized string `inHeap` returns false.
