### ISSUE TITLE
Function ` size_type find( value_type, size_type )` does not return npos when character is not found

### ISSUE THREAD

**Issue by Vizepi** [RobloxResearch/SIMDString#8]
When adding this test:
`EXPECT_EQ(string1.find('f'), simdstring1.find('f'));`
in tests/main.cpp in the `TEST(SIMDStringTest, Find)` section, there is an error.
This is due to find not returning npos, but the delta between memchr result and m_data.
This effectively breaks the possibility to do tests like this:
```C++
if ( myString.find( ' ' ) != SIMDString;;npos ) {
    ...
}
```

**Comment by Vizepi** [comment]
Possible fix is to change find implementation for:
```C++
constexpr size_type find(value_type c, size_type pos = 0) const {
    value_type* pFound = (value_type*)memchr(m_data + pos, c, m_length);
    return pFound == nullptr ? npos : static_cast<size_type>(pFound - m_data);
}
```

**Comment by linwansong** [comment]
This was fixed in https://github.com/RobloxResearch/SIMDString/commit/4d9746301ddb1d36d9874e3bfd2e15da4cd2c22d
