### ISSUE TITLE
Defines in header pollutes global scope

### ISSUE THREAD

**Issue by Vizepi** [RobloxResearch/SIMDString#9]
There are two defines in SIMDString.h that are not undef at the end of the file:
```C++
#define m_allocated m_hider.data
#define m_allocator m_hider
```
This two defines should be undef at the end of the file, just like the `TEMPLATE` define.

**Comment by linwansong** [comment]
This has been fixed in https://github.com/RobloxResearch/SIMDString/commit/80d371c28a504d9283e68e45902a04af77d5783a
